# Generated by Django 5.1.2 on 2024-11-29 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHE', '0002_alter_observationattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationattachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='observationattachment',
            name='file',
            field=models.FileField(upload_to='observation_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])]),
        ),
    ]
