# Generated by Django 5.1.2 on 2024-10-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHE', '0002_feedback_sheobservation_audittrail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('administrator', 'Administrator')], default='user', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
