# Generated by Django 5.1.2 on 2024-10-15 09:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHE', '0003_remove_customuser_name_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationActionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('action', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tracking_entries', to=settings.AUTH_USER_MODEL)),
                ('she_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='SHE.sheobservation')),
            ],
            options={
                'verbose_name': 'Observation Action Tracking',
                'verbose_name_plural': 'Observation Action Trackings',
                'ordering': ['-date'],
            },
        ),
    ]
