# Generated by Django 5.1.2 on 2024-10-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHE', '0004_observationactiontracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheobservation',
            name='deadline',
        ),
    ]
